##########################################################
##########################################################
##                    ____________                      ##
##                    |  _  \ ___ \                     ##
##                    | | | | |_/ /                     ##
##                    | | | | ___ \                     ##
##                    | |/ /| |_/ /                     ##
##                    |___/ \____/                      ##
##########################################################
##########################################################

## Notes ##
## http://stackoverflow.com/questions/35454814/how-to-use-secrets-yml-in-ruby-on-rails-4-to-store-a-password-in-database-yml
## Can use Rails.application.secrets IF referencing hash:
## Rails.application.secrets[:db][:name]

##########################################################
##########################################################
##########################################################

# Default
default: &default
  pool:     5
  timeout:  5000

##########################################################
##########################################################

# Development
dev: &dev
  adapter:  sqlite3

# Production
prod: &prod
  adapter:  <%= Rails.application.credentials.production[:db][:adpt] %>
  database: <%= Rails.application.credentials.production[:db][:name] %>
  username: <%= Rails.application.credentials.production[:db][:user] %>
  password: <%= Rails.application.credentials.production[:db][:pass] %>
  host:     <%= Rails.application.credentials.production[:db][:host] %>
  port:     <%= Rails.application.credentials.production[:db][:port] %>
  encoding: utf8mb4

##########################################################
##########################################################
##########################################################

development:
  <<: *default
  <<: *dev
  database: db/development.sqlite3

##########################################################

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  <<: *dev
  database: db/test.sqlite3

##########################################################
##########################################################

staging:
  <<: *default
  <<: *prod

##########################################################

production:
  <<: *default
  <<: *prod

##########################################################
##########################################################
